### ISSUE TITLE
🐛 Bug Report - Uncontrol Width Country Select Dropdown

### ISSUE THREAD

**Issue by MHasankhan** [typesnippet/antd-phone-input#107] opened 2024-09-20 17:14 UTC
### Bug description

I used this component in our app, Facing issue to control width of phoneNumber Country Selection Dropdown, If i"ll use classe 'ant-select-dropdown', it'll break other select dropdowns, I have attached the screen shots.
Suggestion:
Add popupClassName and dropdownStyles props in PhoneInput, as antd already provided this prop on Select component

### Reproduction steps

1- Open Country Code Selection dropdown
2-Popup getting width 62px, which breaking the styles

### Screenshots

![image](https://github.com/user-attachments/assets/e77ca14a-4dc9-44e8-a10c-e2a5f90e01cd)

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Mac

**Comment by ArtyomVancyan** [comment] 2024-09-21 12:19
Hi @MHasankhan, I have two questions:

 - Have you tried using the `dropdownRender` option?
 - Can you provide a minimal application repository URL where I can reproduce the issue?
 
P.S. The `dropdownRender` option has been added after noticing a similar issue in the Storybook environment.

**Comment by MHasankhan** [comment] 2024-09-23 07:01
@ArtyomVancyan yes I tried with dropdownRender, but same issue appeared, because dropdown actually the child of ant-select-dropdown, Unfortunately I don't have minimal application repsository url, as its the private repo

**Comment by ArtyomVancyan** [comment] 2024-09-23 08:16
Okay, you can either create a public repo where the problem with styles is reproduced and share the link so I can fix the problem, or you can contribute to the project and recommend your changes. I will review your pull request and release the changes. Please follow the steps below:

 - fork this repository
 - create a new branch for the fix
 - in the [examples](https://github.com/typesnippet/antd-phone-input/tree/master/examples) directory, change one of the applications so your issue is reproduced (or you can just use your private source application for testing)
 - make your changes in the [src/index.tsx](https://github.com/typesnippet/antd-phone-input/blob/master/src/index.tsx) file
 - test how it acts in real world
    * `npm run build` - generates js files and type declarations
    * `npm pack` - generates installable tarball file
    * in package JSON, replace `antd-phone-input` package version with `file:<path-to-cloned-fork>/antd-phone-input-<version>.tgz`
    * delete `node_modules` and `package-lock.json` or `yarn.lock` files, and reinstall the packages
    * run your application and test the results

**Comment by ArtyomVancyan** [comment] 2024-09-30 18:14
@MHasankhan, I decided to close this issue as it occurs only on your side. If you could provide some sample app where I could reproduce the issue, it wouldn't take a few hours to release a version for you. Just check your CSS classes to see if they match with the phone component classes. I assume you use some UI framework, and if you do, usually, this type of problem could come from the layout layer (I know from the experience of working on #49). So, if you decide to contribute or provide a sample app so I can face the problem myself and analyze the cause, you are welcome to reopen this issue.

**Closed by ArtyomVancyan** 2024-09-30 18:14 UTC
Labels: bug
